version: '2.1'

services:

  dash:
    container_name: dash
    hostname: dash
    restart: always
    build: ./dash
    networks:
      tsworker-net:
    expose:
      - "8000"
    command: gunicorn -w 1 -b :8000 app:server # was 8000

  dash1:
    container_name: dash1
    hostname: dash1
    restart: always
    build: ./dash1
    networks:
      tsworker-net:
    expose:
      - "8500"
    command: gunicorn -w 1 -b :8500 app1:server # was 8000

  nginx:
    image: nginx:1.15
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      tsworker-net:
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.http.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=UTC
    depends_on:
      - dash
      - dash1

networks:
  tsworker-net:
    driver: bridge
